---
stages:
  - lint
  - build
  - test
  - push
  - manifest

default:
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  # Default use docker
  tags:
    - docker
  before_script:
    # Authenticate to project registry
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    # Authenticate to Docker Hub repository
    - echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin
